# Generated by Django 5.0.7 on 2024-07-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(help_text='Product Name', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(help_text='Product Name', max_length=50, null=True, unique=True),
        ),
    ]
