# Generated by Django 5.0.7 on 2024-08-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
