# Generated by Django 5.0.7 on 2024-08-04 15:11

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announ', '0002_alter_announcement_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_summernote.fields.SummernoteTextField()),
            ],
        ),
    ]
