# Generated by Django 5.0.7 on 2024-08-04 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announ', '0003_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='content',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='announ.content'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.TextField(),
        ),
    ]
