# Generated by Django 5.0.7 on 2024-08-04 15:47

import django_summernote.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announ', '0004_announcement_content_alter_announcement_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.FileField(upload_to=django_summernote.utils.uploaded_filepath),
        ),
    ]
