# Generated by Django 5.0.7 on 2024-08-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announ', '0006_alter_content_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='content',
            new_name='content2',
        ),
    ]
