# Generated by Django 5.0.7 on 2024-08-04 15:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announ', '0007_rename_content_announcement_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
