# Generated by Django 5.0.7 on 2024-08-04 15:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announ', '0008_announcement_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='text',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
