# Generated by Django 5.0.7 on 2024-08-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announ', '0009_remove_announcement_content2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
