# Generated by Django 5.0.7 on 2024-08-06 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announ', '0011_response_status_response_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
