# Generated by Django 4.2.13 on 2024-07-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nportal', '0006_remove_post_last_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='category name', max_length=255),
        ),
    ]
