# Generated by Django 4.2.13 on 2024-07-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nportal', '0007_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Заголовок нашего поста', max_length=255),
        ),
    ]
