# Generated by Django 5.0.7 on 2024-07-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nportal', '0009_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
