# Generated by Django 5.0.7 on 2024-07-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nportal', '0010_category_name_en_category_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(help_text="Our post's title", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(help_text="Our post's title", max_length=255, null=True),
        ),
    ]
